'use client'

import { useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import type { Product } from '@/lib/products'

type ProductCardProps = { product: Product; images: string[]; onOpen: (product: Product) => void; messageUrl: string }

export function ProductCard({ product, images, onOpen, messageUrl }: ProductCardProps) {
  const [imageIndex, setImageIndex] = useState(0)
  const outOfStock = product.stock === 'Out of Stock' || product.inStock === false
  const nextImage = (direction: number) => setImageIndex((index) => (index + direction + images.length) % images.length)

  return <article className="group flex h-full min-w-0 cursor-pointer flex-col rounded-xl border border-slate-200 bg-white p-3 shadow-md opacity-0 transition-all duration-300 animate-[fade-in_.45s_ease-out_forwards] hover:-translate-y-0.5 hover:shadow-lg dark:border-border dark:bg-card sm:p-4" onClick={() => onOpen(product)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onOpen(product) }} role="button" tabIndex={0} aria-label={`View details for ${product.name}, ${product.color}`}>
    <div className="relative aspect-square w-full overflow-hidden rounded-lg bg-slate-100 dark:bg-muted"><img src={images[imageIndex]} alt={`${product.brand} ${product.name} pickleball paddle in ${product.color}`} className="size-full object-cover transition-transform duration-300 group-hover:scale-[1.03]" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/15 to-transparent" />{product.bestSeller && <span className="absolute left-2 top-2 rounded-full bg-gray-600 px-2.5 py-0.5 text-[10px] font-medium text-white">Best Seller</span>}{outOfStock && <span className="absolute right-2 top-2 rounded-full bg-red-600 px-3 py-1 text-[10px] font-bold text-white sm:text-xs">Out of Stock</span>}{images.length > 1 && <><button type="button" aria-label="Previous product image" className="absolute left-2 top-1/2 size-6 -translate-y-1/2 rounded-full bg-white/80 text-slate-800 opacity-100 sm:opacity-0 sm:group-hover:opacity-100" onClick={(event) => { event.stopPropagation(); nextImage(-1) }}><ChevronLeft className="mx-auto size-4" /></button><button type="button" aria-label="Next product image" className="absolute right-2 top-1/2 size-6 -translate-y-1/2 rounded-full bg-white/80 text-slate-800 opacity-100 sm:opacity-0 sm:group-hover:opacity-100" onClick={(event) => { event.stopPropagation(); nextImage(1) }}><ChevronRight className="mx-auto size-4" /></button><span className="absolute bottom-2 right-2 rounded-full bg-black/55 px-2 py-0.5 text-[10px] font-semibold text-white">{imageIndex + 1}/{images.length}</span></>}</div>
    <div className="flex flex-1 flex-col pt-3 sm:pt-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-muted-foreground sm:text-xs">{product.brand}</p><div className="mt-1 flex items-center justify-between gap-2"><h3 className="min-w-0 truncate text-base font-semibold leading-tight tracking-tight text-slate-800 dark:text-primary sm:text-lg">{product.name}</h3><p className="shrink-0 rounded-full bg-green-50 px-2.5 py-1 text-sm font-semibold text-green-700 dark:bg-green-950/40 dark:text-accent sm:text-base">{product.price}</p></div><p className="mt-2 truncate text-xs text-slate-400 dark:text-muted-foreground">{product.color} <span className="mx-1">·</span> {product.thickness} <span className="mx-1">·</span> {product.core}</p><div className="mt-auto flex gap-2 pt-3"><button type="button" disabled={outOfStock} className="flex min-h-9 flex-1 items-center justify-center gap-1 whitespace-nowrap rounded-md bg-[#1A2C3E] px-2 py-1.5 text-[11px] font-semibold text-white transition-colors hover:bg-[#2A3C4E] disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400 sm:min-h-10 sm:py-2 sm:text-xs" onClick={(event) => { event.stopPropagation(); window.open(messageUrl, '_blank', 'noopener,noreferrer') }}>Message Us</button><button type="button" className="min-h-9 flex-1 rounded-md border border-gray-300 bg-white px-2 py-1.5 text-[11px] font-semibold text-gray-700 transition-colors hover:bg-gray-50 dark:border-border dark:bg-transparent dark:text-primary dark:hover:bg-muted sm:min-h-10 sm:py-2 sm:text-xs" onClick={(event) => { event.stopPropagation(); onOpen(product) }}>Details</button></div></div>
  </article>
}
